import 'package:firebase_core/firebase_core.dart';

import '../../firebase_options.dart';

/// Returns the platform-specific [FirebaseOptions] generated by FlutterFire CLI.
///
/// Delegates to [DefaultFirebaseOptions.currentPlatform], which selects
/// the correct configuration for Android or Web at runtime.
FirebaseOptions resolveFirebaseOptions() {
  return DefaultFirebaseOptions.currentPlatform;
}
