"""Sets up output/<slug>/ from output/<slug>/spec.json.

spec.json:
{
  "track": "happy-beats-business-moves-vol-12-by-ende-dot-app.mp3",
  "shots": ["safety_home", ...],          # stills from the shot harness
  "clips": ["clip_sos_hold", ...],        # encoded clips (+ _first/_last)
  "slides": [["safety_home", ["Run free."], "Someone's got you.", 0], ...],  # 4th: scroll offset
  "cta": ["Run free.", "<em>Someone's got you.</em>"]
}

Creates composition/ (assets only; index.html is written by hand) and
carousel-src/ (assets and a generated index.html).

    python tools/scaffold.py <slug>
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

BRAG = Path(__file__).resolve().parents[1]
REPO = BRAG.parents[1]
SHOTS = REPO / "fitsocial_app" / "tool" / "marketing_shots" / "out"
SKILL = Path.home() / ".claude/plugins/cache/brag/brag/0.4.0/skills/brag/assets"
SDK_FONTS = Path("C:/src/flutter/bin/cache/artifacts/material_fonts")
SFX = ["interface/drop_001.ogg", "interface/drop_002.ogg", "interface/click_002.ogg",
       "interface/select_008.ogg", "impact/impactBell_heavy_000.ogg",
       "impact/impactSoft_medium_001.ogg", "impact/impactSoft_medium_003.ogg",
       "impact/impactGlass_light_002.ogg", "casino/card-slide-2.ogg",
       "casino/card-place-1.ogg", "casino/chips-stack-3.ogg"]


def copy_common(dest: Path):
    (dest / "assets/fonts").mkdir(parents=True, exist_ok=True)
    shutil.copy(REPO / "fitsocial_app/assets/fonts/Anton-Regular.ttf", dest / "assets/fonts")
    for f in ["roboto-regular", "roboto-medium", "roboto-bold", "roboto-bolditalic", "roboto-blackitalic"]:
        shutil.copy(SDK_FONTS / f"{f}.ttf", dest / "assets/fonts")
    shutil.copy(REPO / "fitsocial_app/assets/images/fitsocial_f_mark.png", dest / "assets")
    shutil.copy(BRAG / "kit/kit.js", dest)
    shutil.copy(BRAG / "kit/kit.css", dest)


CAROUSEL = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1350" />
    <title>FitSocial carousel</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      @font-face { font-family: 'Anton'; src: url('assets/fonts/Anton-Regular.ttf'); }
      @font-face { font-family: 'Roboto'; src: url('assets/fonts/roboto-regular.ttf'); font-weight: 400; }
      @font-face { font-family: 'Roboto'; src: url('assets/fonts/roboto-medium.ttf'); font-weight: 500; }
      @font-face { font-family: 'Roboto'; src: url('assets/fonts/roboto-bold.ttf'); font-weight: 700; }
      @font-face { font-family: 'Roboto'; src: url('assets/fonts/roboto-blackitalic.ttf'); font-weight: 900; font-style: italic; }
      html, body { margin: 0; padding: 0; background: #050505; }
    </style>
    <link rel="stylesheet" href="kit.css" />
    <style>
      .fk-type { top: 118px; height: 250px; }
      .fk-line { font-size: 84px; }
      .fk-sub { font-size: 34px; margin-top: 24px; }
      .fk-end { justify-content: center; gap: 34px; }
      .fk-cta { font-family: 'Anton', sans-serif; font-size: 110px; text-transform: uppercase; color: #f7f7f7; line-height: 1.06; text-align: center; }
      .fk-cta em { font-style: normal; color: #ff6b1a; }
    </style>
    <script src="kit.js"></script>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="__DURATION__" data-width="1080" data-height="1350"></div>
    <script>
      // One slide per second, snapshots at n + 0.6; the call to action settles
      // and is taken at the end. Generated by tools/scaffold.py.
      const root = document.getElementById('root');
      const kit = FitKit.create(root, { phoneWidth: 500, phoneTop: 392, statusTime: '05:42' });
      const tl = kit.tl;
      const slides = __SLIDES__;
      const total = slides.length + 1;

      const header = document.createElement('div');
      header.className = 'fk-slide-top';
      header.innerHTML = '<div class="fk-mark-row"><img class="fk-mark" src="assets/fitsocial_f_mark.png" style="height:40px;margin-right:-4px"><div class="fk-word" style="font-size:42px"><span class="fk-it">it</span>Social</div></div><div class="fk-slide-num"></div>';
      root.appendChild(header);
      const num = header.querySelector('.fk-slide-num');
      const label = function (n) { return String(n).padStart(2, '0') + '/' + String(total).padStart(2, '0'); };

      slides.forEach(function (s, i) {
        const pane = kit.pane('s' + i, { still: 'assets/screens/' + s[0] + '.png' });
        // Optional 4th field: scroll the screen up this many logical px so
        // what the headline names is in view above the crop.
        if (s[3]) pane.node.querySelector('img').style.transform = 'translateY(' + (-s[3] * kit.U) + 'px)';
        kit.show('s' + i, i, 'cut');
        kit.headline(i, i + 1, s[1], s[2], { stagger: [0, 0, 0] });
        tl.set(num, { textContent: label(i + 1) }, i);
      });
      kit.phoneIn(0, 0);

      const last = slides.length;
      kit.phoneOut(last - 0.001);
      tl.set(num, { textContent: label(total) }, last);
      const end = kit.wordmark(last, 116, 'assets/fitsocial_f_mark.png', 'Train. Fuel. Share. Grow.');
      const cta = document.createElement('div');
      cta.className = 'fk-cta';
      cta.innerHTML = __CTA__;
      end.insertBefore(cta, end.firstChild);
      gsap.set(cta, { opacity: 0 });
      tl.set(cta, { opacity: 1 }, last);
      tl.set(header, { opacity: 1 }, 0);
      tl.set(header.firstChild, { opacity: 0 }, last);

      window.__timelines['main'] = tl;
    </script>
  </body>
</html>
"""


def main(slug: str):
    out = BRAG / "output" / slug
    spec = json.loads((out / "spec.json").read_text(encoding="utf-8"))

    comp = out / "composition"
    copy_common(comp)
    (comp / "assets/screens").mkdir(exist_ok=True)
    (comp / "assets/clips").mkdir(exist_ok=True)
    (comp / "assets/music").mkdir(exist_ok=True)
    (comp / "assets/sfx").mkdir(exist_ok=True)
    for shot in spec.get("shots", []):
        shutil.copy(SHOTS / f"{shot}.png", comp / "assets/screens")
    for clip in spec.get("clips", []):
        for suffix in [".mp4", "_first.png", "_last.png"]:
            shutil.copy(SHOTS / f"{clip}{suffix}", comp / "assets/clips")
    track = SKILL / "music" / spec["track"]
    shutil.copy(track, comp / "assets/music")
    for sfx in SFX:
        shutil.copy(SKILL / "sfx" / sfx, comp / "assets/sfx")
    subprocess.run([sys.executable, str(BRAG / "tools/audio_data.py"), str(track),
                    str(comp / "assets/audio-data.js"), "30",
                    str(spec.get("musicStart", 0))], check=True)

    car = out / "carousel-src"
    copy_common(car)
    (car / "assets/screens").mkdir(exist_ok=True)
    slides = spec["slides"]
    for s in slides:
        # Stills and clip frames (clip_x_first.png) both live in out/.
        shutil.copy(SHOTS / f"{s[0]}.png", car / "assets/screens")
    html = (CAROUSEL
            .replace("__DURATION__", str(len(slides) + 2.5))
            .replace("__SLIDES__", json.dumps(slides, ensure_ascii=False))
            .replace("__CTA__", json.dumps("<br>".join(spec["cta"]), ensure_ascii=False)))
    (car / "index.html").write_text(html, encoding="utf-8")
    print(f"{slug}: scaffolded, {len(slides)} slides + CTA; carousel last at {len(slides) + 1.2}")


if __name__ == "__main__":
    main(sys.argv[1])
